# This file is deprecated in favor of deploy.yml
name: ci 
on:
  workflow_dispatch:  # Only run manually
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: echo "This workflow is deprecated. Please use deploy.yml instead."

